# Site settings
title: Green-big-frogs Blog
email: greenbigfrog@gmail.com
description: Green-big-frog will post a blog here from time to time...
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://green-big-frog.github.io/blog/" # the base hostname & protocol for your site
twitter_username: greenbigfrog
github_username:  green-big-frog

# Build settings
markdown: kramdown
